### ISSUE TITLE
get-pip.py failed on python2

### ISSUE THREAD

**Issue by ppiyakk2** [swiftstack/vagrant-swift-all-in-one#115]
https://bootstrap.pypa.io/get-pip.py  failed on python2

```
vagrant@saio:~$ curl https://bootstrap.pypa.io/get-pip.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1883k  100 1883k    0     0  3230k      0 --:--:-- --:--:-- --:--:-- 3230k
Traceback (most recent call last):
  File "<stdin>", line 24226, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpXZ7eyH/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
```

Need to change 'cookbooks/swift/recipes/setup.rb'  so that the url is determined by the python version. 

python2
https://bootstrap.pypa.io/2.7/get-pip.py

python3
https://bootstrap.pypa.io/get-pip.py

**Comment by clayg** [comment]
Thank you for reporting the issue!  Any feedback you can give on PR #116 would be appreciated.
